laop/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views
from home.views import ContactSubmissionView,AdvocateSubmissionView

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),
    url(r'^form_submission/', ContactSubmissionView.as_view(), name="contact"),
    url(r'^advocate_form_submission/', AdvocateSubmissionView.as_view(), name="advocate"),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

from wagtail.core.models import Page
from wagtail.core.fields import StreamField
from wagtail.core import blocks
from django import forms
from wagtail.images.blocks import ImageChooserBlock
from wagtail.documents.blocks import DocumentChooserBlock
from wagtail.admin.edit_handlers import MultiFieldPanel, StreamFieldPanel, FieldPanel
from wagtail.snippets.models import register_snippet
from wagtail.snippets.edit_handlers import SnippetChooserPanel
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.core.fields import RichTextField


class HomePage(Page):
    CHOICES = [
        ("m", "Male"),
        ("f", "Female")
    ]
    shift_section_title = models.CharField(max_length=255, null=True)
    shift_section_introduction = models.TextField()
    shift_section = StreamField([('image_title_description', blocks.StructBlock([
        ('sort_order', blocks.IntegerBlock()),
        ('image', DocumentChooserBlock()),
        ('heading', blocks.CharBlock()),
        ('description', blocks.TextBlock()),
        ('forbes_link_description', blocks.TextBlock(required=False)),
        ('forbes_url', blocks.URLBlock(required=False))]))], null=True)
    Where_do_i_start_title = models.CharField(max_length=255, null=True)
    where_do_i_start_introduction = models.TextField()
    laop_consortium_title = models.CharField(null=True, max_length=255)
    laop_consortium_section = StreamField([('image_name_description', blocks.StructBlock([
        ('sort_order', blocks.IntegerBlock()),
        ('name', blocks.CharBlock()),
        ('initial_image', ImageChooserBlock()),
        ('hover_image', ImageChooserBlock()),
        ('sketch_image', ImageChooserBlock()),
        ('brand_identity', blocks.CharBlock()),
        ('designation', blocks.CharBlock(required=False)),
        ('quote', blocks.RichTextBlock(required=False)),
        ('description', blocks.TextBlock()),
        ('solving_for', blocks.TextBlock(required=False)),
        ('gender', blocks.ChoiceBlock(choices=CHOICES, default=CHOICES[0])),
        ('background', blocks.RichTextBlock(required=False))]))], null=True)
    join_the_movement_title = models.CharField(null=True, max_length=255)
    join_the_movement_subtitle = models.CharField(null=True, max_length=255, blank=True)
    join_the_movement_description = RichTextField(null=True, blank=True)

    content_panels = Page.content_panels + [
        MultiFieldPanel(
            [
                FieldPanel('shift_section_title'),
                FieldPanel('shift_section_introduction'),
                StreamFieldPanel('shift_section'),
            ],
            heading='Shift Section'
        ),
        MultiFieldPanel(
            [
                FieldPanel('Where_do_i_start_title'),
                FieldPanel('where_do_i_start_introduction'),
            ],
            heading='Where do i start section'
        ),
        MultiFieldPanel(
            [
                FieldPanel('laop_consortium_title'),
                StreamFieldPanel('laop_consortium_section')
            ],
            heading='LAOP Consortium Section'
        ),
        MultiFieldPanel(
            [
                FieldPanel('join_the_movement_title'),
                FieldPanel('join_the_movement_subtitle'),
                FieldPanel('join_the_movement_description'),
            ],
            heading='Join the movement section'

        )

    ]

    def get_context(self, request):
        context = super(HomePage, self).get_context(request)
        videos = BackgroundVideos.objects.all().order_by('season__name', 'sort_order')
        solutions = Solution.objects.all()
        seasons = Season.objects.all().order_by('-default_season','name')
        solution_category = SolutionCategory.objects.all().order_by('sort_order')
        context.update({
            "videos": videos,
            'solutions': solutions,
            'seasons': seasons,
            'solution_category': solution_category,
        })
        return context

    subpage_types = [
        'home.BookPage',
        'home.AboutPage',
        'home.PartnerPage',
        'home.MediaPage',
        'home.ContactPage',
        'home.JoinPage',
        'home.JoinMovementPage',
        'home.WhitePaperPage',
    ]


@register_snippet
class Solution(models.Model):
    solution_category = models.ForeignKey('SolutionCategory', on_delete=models.SET_NULL, null=True)
    sort_order = models.IntegerField(default=1)
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        on_delete=models.CASCADE,
        related_name='+',
    )
    button_element = models.TextField(null=True, blank=True)

    panels = [
        FieldPanel('solution_category', widget=forms.Select),
        FieldPanel('sort_order'),
        FieldPanel('title'),
        FieldPanel('description'),
        ImageChooserPanel('image'),
        FieldPanel('button_element'),
    ]

    def __str__(self):
        return self.title + ' - ' + self.solution_category.title

    class Meta:
        verbose_name_plural = "Solutions"


class BackgroundVideos(models.Model):
    season = models.ForeignKey('Season', on_delete=models.SET_NULL, null=True)
    solution = models.ForeignKey('Solution', on_delete=models.SET_NULL, null=True, blank=True)
    sort_order = models.IntegerField(default=1)
    heading = models.CharField(max_length=255)
    sub_description = models.TextField()
    description = models.TextField()
    mobile_slider_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        on_delete=models.CASCADE,
        related_name='+',
        help_text='Please upload an image of size 750 x 660 for better view'
    )
    Mp4_video_file = models.FileField(upload_to='uploads/videos', null=True, blank=True)
    Ogv_video_file = models.FileField(upload_to='uploads/videos', null=True, blank=True)
    Webm_video_file = models.FileField(upload_to='uploads/videos', null=True, blank=True)
    popup_vimeo_id = models.CharField(max_length=50, null=True, blank=True)
    popup_youtube_id = models.CharField(max_length=50, null=True, blank=True)
    slider_heading = models.CharField(max_length=255, null=True, blank=True)
    initial_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        on_delete=models.CASCADE,
        related_name='+',
        help_text='Please upload an image of size 300 x 169 for better view'
    )
    popup_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        on_delete=models.CASCADE,
        related_name='+',
        help_text='Please upload an image of size 300 x 169 for better view'
    )
    time = models.CharField(max_length=50, null=True, blank=True)
    category = models.CharField(max_length=255, null=True, blank=True)
    forbes_link = StreamField([('forbes_title_url', blocks.StructBlock([
        ('title', blocks.CharBlock(required=False)),
        ('forbes_url', blocks.URLBlock(required=False))]))], null=True, blank=True)
    linkedin_link = StreamField([('linkedin_title_url', blocks.StructBlock([
        ('title', blocks.CharBlock(required=False)),
        ('linkedin_url', blocks.URLBlock(required=False))]))], null=True, blank=True)

    panels = [
        FieldPanel('season', widget=forms.Select),
        FieldPanel('solution', widget=forms.Select),
        FieldPanel('sort_order'),
        FieldPanel('heading'),
        FieldPanel('sub_description'),
        FieldPanel('description'),
        ImageChooserPanel('mobile_slider_image'),
        FieldPanel('Mp4_video_file'),
        FieldPanel('Ogv_video_file'),
        FieldPanel('Webm_video_file'),
        FieldPanel('popup_vimeo_id'),
        FieldPanel('popup_youtube_id'),
        FieldPanel('slider_heading'),
        ImageChooserPanel('initial_image'),
        ImageChooserPanel('popup_image'),
        FieldPanel('time'),
        FieldPanel('category'),
        StreamFieldPanel('forbes_link'),
        StreamFieldPanel('linkedin_link')
    ]

    def __str__(self):
        return self.heading + " (" + self.season.name + ") "

    class Meta:
        verbose_name_plural = "Background Videos"


class Season(models.Model):
    name = models.CharField(max_length=125)
    coming_soon_text = models.CharField(max_length=125, null=True, blank=True)
    default_season = models.BooleanField("Make as Default Season",default=False)

    panels = [
        FieldPanel('name'),
        FieldPanel("coming_soon_text"),
        FieldPanel("default_season"),
    ]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Seasons"


class BookPage(Page):
    sub_header = models.CharField(max_length=255, null=True, blank=True)
    description = RichTextField(null=True, blank=True)
    listing_page_title = models.TextField()
    listing_page_description = models.TextField()
    listing_page_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        on_delete=models.CASCADE,
        related_name='+',
    )
    price = models.CharField(max_length=30, null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)
    book_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        on_delete=models.CASCADE,
        related_name='+',
    )
    vimeo_video_id = models.CharField(max_length=150, null=True, blank=True)
    youtube_video_id = models.CharField(max_length=150, null=True, blank=True)

    content_panels = Page.content_panels + [
        FieldPanel("sub_header"),
        FieldPanel("price"),
        FieldPanel("release_date"),
        FieldPanel("description"),
        FieldPanel('listing_page_title'),
        FieldPanel('listing_page_description'),
        ImageChooserPanel("listing_page_image"),
        ImageChooserPanel("book_image"),
        FieldPanel("vimeo_video_id"),
        FieldPanel("youtube_video_id"),
    ]

home/forms.py
from django import forms


class ContactPageForm(forms.Form):
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    job_title = forms.CharField(max_length=100, required=False)
    company= forms.CharField(max_length=255, required=False)
    email= forms.EmailField(required=True)
    phone = forms.CharField(max_length=100)
    comment = forms.CharField(widget=forms.Textarea,required=False) 
    message = forms.CharField(widget=forms.Textarea,required=False) 

class AdvocatePageForm(forms.Form):
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    job_title = forms.CharField(max_length=100, required=False)
    company= forms.CharField(max_length=255, required=False)
    email= forms.EmailField(required=True)
    phone = forms.CharField(max_length=100)
    comment = forms.CharField(widget=forms.Textarea,required=False) 
    message = forms.CharField(widget=forms.Textarea,required=False) 
    being_advocate = forms.CharField(widget=forms.Textarea,required=False) 

home/views.py
from django.views.generic import FormView
from django.contrib import messages
from .forms import ContactPageForm,AdvocatePageForm
from home.models import ContactForm, ContactPage, BecomeAdvocateForm
# from django.http import JsonResponse
from home.utils import EmailManager
from django.conf import settings


class ContactSubmissionView(FormView):
    form_class = ContactPageForm
    template_name = "home/contact_page.html"
    manager_mail_subject = "Confirmation Email – Automatic Email"
    manager_mail_template = "home/email/contact_page_details.html"
    manager_subject = "LAOP - Contact Form"
    manager_data_template = "home/email/manager_email_content.html"

    def get_success_url(self):
        page_url = ContactPage.objects.filter(live=True)[0].url
        return page_url

    def form_valid(self, form):
        contact_form_obj = ContactForm()
        contact_form_obj.first_name = form.cleaned_data['first_name']
        contact_form_obj.last_name = form.cleaned_data['last_name']
        contact_form_obj.job_title = form.cleaned_data['job_title']
        contact_form_obj.company = form.cleaned_data['company']
        contact_form_obj.email = form.cleaned_data['email']
        contact_form_obj.phone = form.cleaned_data['phone']
        contact_form_obj.comment = form.cleaned_data['comment']
        contact_form_obj.message = form.cleaned_data['message']
        contact_form_obj.save()
        mail_context = {}
        self.email_manager = EmailManager(request=self.request)
        mail_context.update({
            "form": form,
        })
        send_mail = [ contact_form_obj.email ]
        self.email_manager.send_manager_email(subject=self.manager_subject,
                                              options=mail_context,
                                              to=settings.MANAGER_LIST,
                                              template=self.manager_data_template,
                                              )
        return super(ContactSubmissionView, self).form_valid(form)

    def form_invalid(self, form):
        return super(ContactSubmissionView, self).form_invalid(form)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            #messages.add_message(request, messages.INFO, "Thank you for contacting us")
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class AdvocateSubmissionView(FormView):
    form_class = AdvocatePageForm
    template_name = "home/join_page.html"
    manager_mail_subject = "LAOP Advocate Application Confirmation"
    manager_mail_template = "home/email/contact_page_details.html"
    manager_subject = "LAOP - Advocate Application Form"
    manager_data_template = "home/email/advocate_email.html"

    def get_success_url(self):
        page_url = ContactPage.objects.filter(live=True)[0].url
        return page_url

    def form_valid(self, form):
        contact_form_obj = BecomeAdvocateForm()
        contact_form_obj.first_name = form.cleaned_data['first_name']
        contact_form_obj.last_name = form.cleaned_data['last_name']
        contact_form_obj.job_title = form.cleaned_data['job_title']
        contact_form_obj.company = form.cleaned_data['company']
        contact_form_obj.email = form.cleaned_data['email']
        contact_form_obj.phone = form.cleaned_data['phone']
        contact_form_obj.comment = form.cleaned_data['comment']
        contact_form_obj.message = form.cleaned_data['message']
        contact_form_obj.being_advocate = form.cleaned_data['being_advocate']
        contact_form_obj.save()
        mail_context = {}
        self.email_manager = EmailManager(request=self.request)
        mail_context.update({
            "form": form,
        })
        send_mail = [ contact_form_obj.email ]
        self.email_manager.send_manager_email(subject=self.manager_mail_subject,
                                              options=mail_context,
                                              to=send_mail,
                                              template=self.manager_mail_template,
                                              )
        self.email_manager.send_manager_email(subject=self.manager_subject,
                                              options=mail_context,
                                              to=settings.MANAGER_LIST,
                                              template=self.manager_data_template,
                                              )
        return super(ContactSubmissionView, self).form_valid(form)

    def form_invalid(self, form):
        return super(ContactSubmissionView, self).form_invalid(form)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            #messages.add_message(request, messages.INFO, "Thank you for contacting us")
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

home/templates/home/about_page.html
{% extends "base.html" %}
{% load static %}
{% load wagtailcore_tags wagtailimages_tags %}
{% block body_class %}template-aboutpage{% endblock %}
{% block content %}
{% image page.image original as imag %}
<section class="meet_glenn_sections top_header_margin" style="background:#000 url({{ imag.url }}) no-repeat bottom left;">
    <div class="right_text_section">
        <h1> {{ page.heading }} </h1>
        <p> {{ page.description }} </p>
        <a href="https://www.glennllopis.com/" target="_blank">Learn more <span>on www.glennllopis.com</span></a>
    </div>
    <div class="clear"></div>
</section>
<section class="about_section">
    <div class="our_team_section">
        <div class="container">
            {% for item in page.title_with_desc %}
                {% if item.value.heading %}
                    <h2> {{ item.value.heading }} </h2>
                {% endif %}
                {% if item.value.description %}
                    <p> {{ item.value.description }} </p>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</section>
<section class="our_team_section aboutpage_section">
    <div class="container">
        <h2 class="about_section_team">Our Leadership Team</h2>
        <div class="flex_section">
            {% for teamdetail in team %}
                <div class="team_content">
                    <div class="team_img_section">
                        {% image teamdetail.initial_image original as img %}
                        <img class="left_img over" src="{{ img.url }}" alt="{{ img.image }}" data-wow-delay="0.1s">
                        {% image teamdetail.teamimage_thumbnail original as thumb_img %}
                        <img class="under" src="{{ thumb_img.url }}" alt="{{ thumb_img.image }}">
                        <span class="overlay"></span>
                        {% if teamdetail.gender == 'm' %}
                            <a href="" class="h2_left popup_triggers" data-id= "{{ teamdetail.sort_order }}"  data-class="teampopup">What is he solving for? </a>
                        {% else %}
                            <a href="" class="h2_left popup_triggers" data-id= "{{ teamdetail.sort_order }}"  data-class="teampopup">What is she solving for? </a>
                        {% endif %}
                    </div>
                    <p class="name_text"> {{ teamdetail.team_name }} </p>
                    {% if teamdetail.team_designation %}
                        <p class="desg_text"> {{ teamdetail.team_designation }} </p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
    {% for teamdetail in team %}
        <div class="content_popup_wrapper hide" id= "{{ teamdetail.sort_order }}">
            <a href="#" class="close_ic"><i class="icon icon-close"></i></a>
            <div class ="content_wrapper">
                <div class="img_section">
                    <div class="name_block mobile">
                        <h2> {{ teamdetail.team_name }} </h2>
                        <p class="small_text"> {{ teamdetail.team_designation }} </p>
                    </div>
                    {% image teamdetail.teamimage original as img %}
                    <img src="{{ img.url }}" alt="noimg">
                </div>
                <div class="content_section">
                    <div class="name_block desktop">
                        <h2> {{ teamdetail.team_name }} </h2>
                        {% if teamdetail.team_designation %}
                            <p class="small_text">{{ teamdetail.team_designation }}</p>
                        {% endif %}
                    </div>
                    {% if teamdetail.solving_for %}
                        {% if teamdetail.gender == 'm' %}
                            <h3> What is he solving for? </h3>
                        {% else %}
                            <h3> What is she solving for? </h3>
                        {% endif %}
                        <p class="bold_txt">{{ teamdetail.solving_for }}</p>
                    {% endif %}
                    {% if teamdetail.background|striptags %}
                        <h3>Background</h3>
                        <p> {{ teamdetail.background|richtext }} </p>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
</section>
{% endblock %}

home/templates/home/book_page.html
{% extends "base.html" %}
{% load static %}
{% load wagtailcore_tags wagtailimages_tags %}

{% block body_class %}template-bookpage{% endblock %}

{% block content %}
<section class="top_book_section top_header_margin">
    <div class="book_container">
        <div class="left_img_section">
            {% image page.book_image original %}
        </div>
        <div class="right_content_section">
            <div class="book_description">
                <h1> {{ page.title }} </h1>
                {% if page.sub_header %}
                    <h2>  {{ page.sub_header }} </h2>
                {% endif %}
                {% if page.description|striptags %}
                    {{ page.description|richtext }}
                {% endif %}
            </div>
            <div class="order_section">
                    <img src="{% static 'graphics/amazone.png' %}" alt="amazone">
                    {% if page.price %}
                        <p class="price"> ${{ page.price }} </p>
                    {% endif %}
                {% if page.release_date %}
                    <div class="left">
                        <p class="small_txt">The book will be released on {{ page.release_date|date:"F d, Y" }} </p>
                    </div>
                {% endif %}
                <div class="right">
                    <a href="https://www.amazon.com/gp/product/1733812512/ref=dbs_a_def_rwt_bibl_vppi_i1" target="_blank">Order Now!</a>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</section>
<section class="bottom_video_section">
    <div class="video_frame">
        {% if page.vimeo_video_id %}
            <iframe src="//player.vimeo.com/video/{{ page.vimeo_video_id }}" ></iframe>
        {% elif page.youtube_video_id %}
            <iframe src="http://www.youtube.com/embed/{{ page.youtube_video_id }} "></iframe>
        {% endif %}
    </div>
</section>

{% endblock %}

home/templates/home/contact_page.html
{% extends "base.html" %}

{% load static wagtailuserbar wagtailcore_tags wagtailimages_tags home_tags %}
{# {% load base_tags %} #}
{% block content %}
<section class="contact_section top_header_margin">
    <div id="pop-up-window" class="pop_up_contact">
        <div class="pop_up_content">
            <div class="pop_up_container">
                <span class="icon-close_popup pop-up-close"></span>
                <p class="popup_head">Thank you for contacting us!</p>
                <p>Your request has been received and one of our team members will reply to you within 2 business days.</p>
                <p>If you need immediate assistance, please contact us at <a href="tel:(949) 842-6204">(949) 842-6204.</p>
                <a class="nav_button" href="/">Go to home</a>
            </div>
        </div>
    </div>
    <div class="container">
        <h1> <span class="special_case">| </span>{{ page.title|custom_title|safe }} </h1>
        <p> {{ page.intro }} </p>
        <form action="/form_submission/" method="POST" role="form" id="contact_form" class="contact_us_form">
            {% csrf_token %}
            <div class="name_section">
                <input type="text" name="first_name" placeholder="First Name*" maxlength="150" required="" id="id_first_name" class="contact_input inputText">
                <input type="text" name="last_name" placeholder="Last Name*" maxlength="150" required="" id="id_last_name" class="contact_input inputText">
            </div>
            <div class="clear"></div>
            <input type="text" name="job_title" placeholder="Job Title*" maxlength="100" id="id_job_title" required="" class="contact_input inputText">
            <input type="text" name="company" placeholder="Company*" required="" maxlength="255" id="id_company" class="contact_input inputText">
            <div class="name_section">
                <input type="email" name="email" placeholder="Email*" required="" id="id_email" class="contact_input inputText">
                <input type="tel" name="phone" placeholder="Phone*" maxlength="100" required="" id="id_phone" class="contact_input inputText us_phone">
            </div>
            <input type="text" name="comment" required="" placeholder="How did you hear about us?*" id="id_comment" class="contact_input inputText">
            <input type="text" name="message" required="" placeholder="Message*" id="id_message" class="contact_input inputText">
            <div class="contact_btn">
                <input type="submit" class="btn_submit" id="contact_btn_txt" value="Submit"></inpout>
            </div>
        </form>
        {% if messages %}
            {% for message in messages %}
              <p class="success_msg" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        {% endif %}
    </div>
</section>
{% endblock %}

home/templates/home/join_page.html
{% extends "base.html" %}

{% load static wagtailuserbar wagtailcore_tags wagtailimages_tags home_tags %}
{# {% load base_tags %} #}
{% block content %}
<section class="contact_section top_header_margin">
    <div id="pop-up-window" class="pop_up_contact">
        <div class="pop_up_content">
            <div class="pop_up_container">
                <span class="icon-close_popup pop-up-close"></span>
                <p class="popup_head">Thank you for completing the Advocate application.</p>
                <p>One of our team members will contact you shortly to inform you about the status of your application.</p>
                <a class="nav_button join_page" href="/">Back to home</a>
            </div>
        </div>
    </div>
    <div class="container">
        <h1> <span class="special_case">| </span>{{ page.title|custom_title|safe }} </h1>
        <p> {{ page.intro }} </p>
        <form action="/advocate_form_submission/" method="POST" role="form" id="contact_form">
            {% csrf_token %}
            <div class="name_section">
                <input type="text" name="first_name" placeholder="First Name*" maxlength="150" required="" id="id_first_name" class="contact_input  inputText">
                <input type="text" name="last_name" placeholder="Last Name*" maxlength="150" required="" id="id_last_name" class="contact_input  inputText">
            </div>
            <div class="clear"></div>
            <input type="text" name="job_title" placeholder="Job Title*" maxlength="100" id="id_job_title" required="" class="contact_input inputText">
            <input type="text" name="company" placeholder="Company*" maxlength="255" id="id_company" required="" class="contact_input inputText">
            <div class="name_section">
                <input type="email" name="email" placeholder="Email*" required="" id="id_email" class="contact_input  inputText">
                <input type="tel" name="phone" placeholder="Phone*" maxlength="100" required="" id="id_phone" class="contact_input  inputText us_phone">
            </div>
            <input type="text" name="comment" placeholder="What does personalization mean to you?*"  id="id_comment" required="" class="contact_input inputText">
            <input type="text" name="message" placeholder="How does personalization influence the ways you work and lead?*" id="id_message" required="" class="contact_input inputText">
            <input type="text" name="being_advocate" placeholder="Why would you like to become an Advocate?*"  id="id_being_advocate" required="" class="contact_input inputText">
            <div class="contact_btn">
                <input type="submit" class="btn_submit" id="contact_btn_txt" value="Submit"></inpout>
            </div>
        </form>
        {% if messages %}
            {% for message in messages %}
              <p class="success_msg" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        {% endif %}
    </div>
</section>
{% endblock %}

home/templates/home/partner_page.html
{% extends "base.html" %}
{% load static home_tags %}
{% load wagtailcore_tags wagtailimages_tags %}

{% block body_class %}template-partnerpage{% endblock %}

{% block content %}
<section class = "partner_section top_header_margin">
    <div class="container">
        <div class="description rich_text testimonial_div">
            <h1><span class="special_case">| </span>{{ page.title|custom_title|safe }}</h1>
            <p>{{ page.description }}</p>
            {% for partner in page.partner_details %}
                <div class="partners_sections">
                        <div class="partner_imgsection">
                            {% image partner.value.image original as img %}
                            {% if partner.value.image %}
                                    <img src="{{ img.url }}" alt="no_img">
                            {% else %}
                                    <img src="" alt="no_img">
                            {% endif %}
                        </div>
                        <div class="partner_txts">
                            <span class="partner_title">{{ partner.value.heading }}</span>
                            <div class="text_align rich_text description">{{ partner.value.description|safe }}</div>
                            <a class="forbes_link" href="{{ partner.value.forbes_url}}" target="_blank">Read more on Forbes</a>
                        </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}